/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/art_gallery.glb --transform 
Files: public/models/art_gallery.glb [187.69MB] > C:\PROJECT\Mosaic\Frontend\art_gallery-transformed.glb [1.86MB] (99%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/art_gallery-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.001']} position={[0, 6, 0]} />
      <mesh geometry={nodes.Plane.geometry} material={materials.Material} />
    </group>
  )
}

useGLTF.preload('/art_gallery-transformed.glb')
